from math import sqrt

from .paths import ENTITIES_DIR, MAP_DIR

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

FPS = 60

ZOOM = 4
TILE_SIZE = 16
PLAYER_SPEED = 200

PLAYER_W = 32
PLAYER_H = 32

VECTOR_NORM = 1 / sqrt(2)

HITBOX_W = PLAYER_W
HITBOX_H = 6

WALK_FRAME_DURATION = 0.18

VIEW_W = SCREEN_WIDTH // ZOOM
VIEW_H = SCREEN_HEIGHT // ZOOM

MAP_PATH = MAP_DIR / "mapa.tmx"
PLAYER_DIR = ENTITIES_DIR / "player"
